u1 = User.create(name: "bob" ,email: "bobby@hot.com" ,password: "bobo")
u2 = User.create(name: "emmy" ,email: "emmy@hot.com" ,password: "emem")
u3 = User.create(name: "john", email: "johnny@hot.com", password: "jojo")
e1= Event.create(name: "Camp Flog Gnaw Carnival" ,dis: "formerly known as the OFWGKTA Carnival", user_id: u1.id )
e2= Event.create(name: "Gov Ball" ,dis: "music festival held in Randall's Island, New York City, USA", user_id: u2.id )
e3= Event.create(name: "Rolling Loud", dis: "Rolling Loud is a recurring music festival held in the United States of America.", user_id: u2.id)
r1 = RSVP.create(event_id: e2.id, user_id: u2.id, invite_id: u3.id, rsvp_type: "Invited")
r2 = RSVP.create(event_id: e2.id, user_id: u1.id, invite_id: u3.id, rsvp_type: "Invited")